### ISSUE TITLE
Backslashes in restore directory?

### ISSUE THREAD

**Issue by hakong** [grke/burp#790] opened 2019-01-14 19:39 UTC
Restoring from a windows client to a windows machine like this:
```burp -a r -r "C:/Users/User1/" -d C:/Users/User1/restore/ -C "LAPTOP-User1"```
but I would like to skip restoring C:/Users/User1/Videos/, since that folder is huge and I don't need to restore it.

Is there an easy exclude regex I can use on a oneliner command?

**Comment by grke** [comment] 2019-01-15 07:41
Maybe this can be good enough?

'C:/Users/User1/[^V]'

**Comment by hakong** [comment] 2019-01-15 09:42
I tried, dosen't seem to work.
```
C:\Program Files\Burp\bin>burp -a r -r "C:/Users/User1/[^V]" -d "C:\TEMP\" -C "LAPTOP-User1"
2019-01-15 09:41:06: burp[3748] No backup specified. Using the most recent.
2019-01-15 09:41:06: burp[3748] Connecting to burp.server:4971
2019-01-15 09:41:06: burp[3748] auth ok
2019-01-15 09:41:06: burp[3748] Server version: 2.1.32
2019-01-15 09:41:06: burp[3748] nocsr ok
2019-01-15 09:41:06: burp[3748] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

2019-01-15 09:41:06: burp[3748] extra_comms_begin ok:autoupgrade:incexc:orig_client:uname:sincexc:counters_json:msg:csetproto:rshash=blake2:
2019-01-15 09:41:06: burp[3748] Server has protocol=0 (auto)
2019-01-15 09:41:06: burp[3748] Using protocol=1
2019-01-15 09:41:06: burp[3748] doing restore 0:C:/Users/User1/[^V]
2019-01-15 09:41:06: burp[3748] doing restore confirmed


--------------------------------------------------------------------------------
Start time: 2019-01-15 09:41:06
  End time: 2019-01-15 09:41:07
Time taken: 00:01
                             Attempted | Expected
                   ------------------------------
                   ------------------------------

             Messages:             0
             Warnings:             0

      Bytes estimated:             0
      Bytes attempted:             0
       Bytes received:          1401 (1.37 KB)
           Bytes sent:           849
--------------------------------------------------------------------------------
2019-01-15 09:41:07: burp[3748] restore finished
```

**Comment by grke** [comment] 2019-01-15 12:51
Hello,

It works for me, but I haven't had a chance to try it on Windows.

If you are trying a few things out, it is helpful to do a list first instead of a restore, because you can see what you will get with the restore. For example:

burp -a l -b 4 -r '/home/graham/testdir6/[^V]'

Then when you are ready, you can '-a r' instead of 'a l'.

What do you get if you try this:

burp -a l -r "C:/Users/User1" -C "LAPTOP-User1"

**Comment by hakong** [comment] 2019-01-15 13:12
I see what I was doing wrong.
Works:
```burp -a r -r "C:/Users/User1/[^V]" -d "C:/TEMP/" -C "LAPTOP-User1"```

Fails without error:
```burp -a r -r "C:/Users/User1/[^V]" -d "C:\TEMP\" -C "LAPTOP-User1"```

Just the forward/reverse slashes. Burp could maybe print an error though. When using reverse slashes it outputs this:
```
C:\Program Files\Burp\bin>burp -a r -r "C:/Users/User1/[^V]" -d "C:\TEMP\" -C "LAPTOP-User1"
2019-01-15 13:09:07: burp[16272] No backup specified. Using the most recent.
2019-01-15 13:09:07: burp[16272] Connecting to burp.server:4971
2019-01-15 13:09:07: burp[16272] auth ok
2019-01-15 13:09:07: burp[16272] Server version: 2.1.32
2019-01-15 13:09:07: burp[16272] nocsr ok
2019-01-15 13:09:07: burp[16272] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

2019-01-15 13:09:07: burp[16272] extra_comms_begin ok:autoupgrade:incexc:orig_client:uname:sincexc:counters_json:msg:csetproto:rshash=blake2:
2019-01-15 13:09:07: burp[16272] Server has protocol=0 (auto)
2019-01-15 13:09:07: burp[16272] Using protocol=1
2019-01-15 13:09:07: burp[16272] doing restore 0:C:/Users/User1/[^V]
2019-01-15 13:09:07: burp[16272] doing restore confirmed


--------------------------------------------------------------------------------
Start time: 2019-01-15 13:09:07
  End time: 2019-01-15 13:09:08
Time taken: 00:01
                             Attempted | Expected
                   ------------------------------
                   ------------------------------

             Messages:             0
             Warnings:             0

      Bytes estimated:             0
      Bytes attempted:             0
       Bytes received:          1401 (1.37 KB)
           Bytes sent:           849
--------------------------------------------------------------------------------
2019-01-15 13:09:08: burp[16272] restore finished

```

**Comment by hakong** [comment] 2019-01-18 09:47
@grke Just remembered I wanted to keep this open. Burp should print an error message of some sort when this happens. Do you want to move this to another issue with a more descriptive title?

**Comment by grke** [comment] 2019-01-22 10:17
Hello,
I have just renamed this issue, so that's OK.
I will try to reproduce the behaviour when I get some time.
Thank you.

**Comment by grke** [comment] 2019-02-01 23:22
Hello,

I am using 2.2.16, and everything seems 99% fine.

These all work:
```
burp.exe -a r -r "C:/Program Files/[^V]" -d "C:/TEMP/" -C "LAPTOP-User1"
burp.exe -a r -r "C:/Program Files/[^V]" -d "C:/TEMP" -C "LAPTOP-User1"
burp.exe -a r -r "C:/Program Files/[^V]" -d C:/TEMP -C "LAPTOP-User1"
burp.exe -a r -r "C:/Program Files/[^V]" -d C:/TEMP/ -C "LAPTOP-User1"
burp.exe -a r -r "C:/Program Files/[^V]" -d "C:\TEMP" -C "LAPTOP-User1"
burp.exe -a r -r "C:/Program Files/[^V]" -d C:\TEMP -C "LAPTOP-User1"
burp.exe -a r -r "C:/Program Files/[^V]" -d C:\TEMP\ -C "LAPTOP-User1"
```

This doesn't work:
```
burp.exe -a r -r "C:/Program Files/[^V]" -d "C:\TEMP\" -C "LAPTOP-User1"
```
However, burp prints a message:

```
2019-02-02 09:15:14: burp.exe[3764] C:\TEMP" -C LAPTOP-User1: Could not get realpath in get_desired_restore_dir: Permission denied
```

This realpath business is new in recent versions of burp-2.2.x, but it makes it clear that the backslash before the double quote at the end of "C:\TEMP\" results in the rest of the line being treated as the directory that you want to restore to.

I think that the client side should mention the directory that it thinks you want to restore to as part of the normal output. If it had done that, I think things would have been much clearer from the beginning.

I will do that soon.

**Comment by grke** [comment] 2019-02-03 11:02
Output updated in master. Now closing.

**Closed by grke** 2019-02-03 11:02 UTC
