### ISSUE TITLE
Error backing up: SSL read problem in asfd_do_read_ssl

### ISSUE THREAD

**Issue by remcoluit** [grke/burp#550] opened 2017-03-27 05:38 UTC
I use Burp for backing up several different machines (Windows, Linux). Recently upgraded all from 1.3.48 to 2.0.54. One Windows SBS2011 machine is now having trouble backing up. On that server there are 5 backup jobs from which 2 are failing (client message below). 
What i did:
I ran the server in Foreground mode, but there are no messages. 
I tried 1.3.48 and 2.1.4 on the client which makes no difference.
Renamed the certificates on client and server so they get regenerated.
Removed all files from server so it acts as a new backup.

I'm out of ideas, attached the error from the server and the client:

Most of the times the server keeps running (until socket timeout) and i can see the log. In which i think the number of Changed/Unchanged files is swapped.

The SERVER:
burp monitor 2.0.54                                     
2017-03-27 07:33:24     
Client: nomasrv1exchlogs    
Status: running    
Backup: 0000003 2017-03-27 07:25:40    
Browse: Backup stats     
Start time: 2017-03-27 05:25:39      
End time: 2017-03-27 05:33:24    
Time taken: 07:45                          
New   Changed Unchanged   Deleted     Total   Scanned              
Files        31       376         3        27       410      1248        
Grand total        31       376         3        27       410      1248     
Percentage complete: 32%         
Bytes estimated:   2736567716  (2.55 GB)                  
Bytes:   1722222404  (1.60 GB)

The CLIENT:
2017-03-27 07:25:39: burp[15232] c:\Program Files\Burp\burpexchlogs.conf: status
_port unset
2017-03-27 07:25:39: burp[15232] auth ok
2017-03-27 07:25:39: burp[15232] Server version: 2.0.54
2017-03-27 07:25:39: burp[15232] nocsr ok
2017-03-27 07:25:39: burp[15232] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384
TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

2017-03-27 07:25:39: burp[15232] extra_comms_begin ok:autoupgrade:incexc:orig_cl
ient:uname:counters_json:msg:csetproto:
2017-03-27 07:25:39: burp[15232] Server has protocol=0 (auto)
2017-03-27 07:25:39: burp[15232] Using protocol=1
2017-03-27 07:25:40: burp[15232] Compression level: 9
2017-03-27 07:25:40: burp[15232] do backup client
2017-03-27 07:25:40: burp[15232] Using librsync hash md4
2017-03-27 07:25:40: burp[15232] Control handler registered.
Generate VSS snapshots.
Driver="VSS Vista", Drive(s)="D"
2017-03-27 07:26:04: burp[15232] VSS drive letters: 0
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "Task Scheduler
Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "VSS Metadata St
ore Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "Performance Cou
nters Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "System Writer",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "SqlServerWriter
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "ASR Writer", St
ate: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "FSRM Writer", S
tate: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "WMI Writer", St
ate: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "FRS Writer", St
ate: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "Shadow Copy Opt
imization Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "IIS Config Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "COM+ REGDB Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "NPS VSS Writer"
, State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "Microsoft Excha
nge Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "NTDS", State: 0
x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "Certificate Aut
hority", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "IIS Metabase Wr
iter", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "Registry Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "MSSearch Servic
e Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "TS Gateway Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] VSS Writer (PrepareForBackup): "Dhcp Jet Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:26:04: burp[15232] Phase 1 begin (file system scan)

ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 64
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 128
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 192
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 256
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 320
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 384
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 448
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 512
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 576
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 640
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 704
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 768
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 832
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 896
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 960
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1024
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1088
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1152
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1216
ffffffffffffffffffffffffffffffff 1248

2017-03-27 07:26:06: burp[15232] Phase 1 end (file system scan)
2017-03-27 07:26:06: burp[15232] Phase 2 begin (send backup data)

zzzfffffffffffffffffffffffffffffff2017-03-27 07:28:06: burp[15232] main socket:
Got SSL_ERROR_SYSCALL
2017-03-27 07:28:06: burp[15232] main socket: SSL write problem in asfd_do_write
_ssl: 5 - 0=No error
2017-03-27 07:28:06: burp[15232] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 07:28:06: burp[15232] main socket: SSL read problem in asfd_do_read_s
sl: 5 - 0=No error
 34

--------------------------------------------------------------------------------

Start time: 2017-03-27 07:25:39
  End time: 2017-03-27 07:28:06
Time taken: 02:27
                         New   Changed Duplicate   Deleted     Total |  Scanned
                   ------------------------------------------------------------
             Files:       31         3         0         0        34 |     1248
       Grand total:       34         3         0         0        37 |     1248
                   ------------------------------------------------------------

             Messages:             0
             Warnings:             0

      Bytes estimated:    2736567716 (2.55 GB)
      Bytes in backup:      33569828 (32.01 MB)
       Bytes received:         22777 (22.24 KB)
           Bytes sent:      28725891 (27.40 MB)
--------------------------------------------------------------------------------

2017-03-27 07:28:06: burp[15232] Error in phase 2
2017-03-27 07:28:06: burp[15232] Phase 2 end (send file data)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "Task Scheduler Wr
iter", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "VSS Metadata Stor
e Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "Performance Count
ers Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "System Writer", S
tate: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "SqlServerWriter",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "ASR Writer", Stat
e: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "FSRM Writer", Sta
te: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "Microsoft Exchang
e Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "Dhcp Jet Writer",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "Registry Writer",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "FRS Writer", Stat
e: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "COM+ REGDB Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "IIS Config Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "WMI Writer", Stat
e: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "Shadow Copy Optim
ization Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "IIS Metabase Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "MSSearch Service
Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "Certificate Autho
rity", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "TS Gateway Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "NPS VSS Writer",
State: 0x1 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] VSS Writer (BackupComplete): "NTDS", State: 0x1
 (VSS_WS_STABLE)
2017-03-27 07:28:11: burp[15232] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 07:28:11: burp[15232] main socket: SSL read problem in asfd_do_read_s
sl: 5 - 0=No error

**Comment by grke** [comment] 2017-03-27 06:13
I have noticed that changed/unchanged is swapped too.

Is there anything in the server side backup log?
Inside /var/spool/burp/burpexchlogs/working/log?


I wonder if the server child is segfaulting.

You said you ran the server in the foreground. You can also try it in no-fork mode like this - it will make it easy to spot if there is a segfault:

burp -c /etc/burp/burp-server.conf -F -n

You would also need stdout=1 in burp-server.conf to see any output on stdout.

**Comment by remcoluit** [comment] 2017-03-27 06:29
Stdout was 0, therefore i didn't see anything. Forgot to say that i really like Burp!
Server side backup log:
2017-03-27 07:50:00: burp[19165] Client version: 2.0.54
2017-03-27 07:50:00: burp[19165] Protocol: 1
2017-03-27 07:50:00: burp[19165] Client is Windows
2017-03-27 07:50:00: burp[19165] Begin phase1 (file system scan)
2017-03-27 07:50:23: burp[19165] End phase1 (file system scan)
2017-03-27 07:50:23: burp[19165] Begin phase2 (receive file data)
2017-03-27 08:10:40: burp[19165] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:10:40: burp[19165] main socket: SSL read problem in asfd_do_read_ssl: 5 - 110=Connection timed out
2017-03-27 08:10:40: burp[19165] error in do_stuff_to_receive
2017-03-27 08:13:32: burp[19165] End phase2 (receive file data)
2017-03-27 08:13:32: burp[19165] error in backup phase 2

Output from burp -c /etc/burp/burp-server.conf -F -n (removed email and ip address)
2017-03-27 08:24:00: burp[19204] Connect from peer: ::ffff:x.x.x.x:58098
2017-03-27 08:24:00: burp[19204] auth ok for: nomasrv1exchlogs
2017-03-27 08:24:00: burp[19204] Client nomasrv1exchlogs does not want a certificate signed
2017-03-27 08:24:00: burp[19204] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

2017-03-27 08:24:00: burp[19204] Server is using protocol=0 (auto)
2017-03-27 08:24:00: burp[19204] Client supports being sent json counters.
2017-03-27 08:24:00: burp[19204] Client has set protocol=1
2017-03-27 08:24:00: burp[19204] found old working directory: /home/backup/nomasrv1exchlogs/0000003 2017-03-27 07:50:00
2017-03-27 08:24:00: burp[19204] working_dir_recovery_method: delete
2017-03-27 08:24:00: burp[19204] deleting old working directory
2017-03-27 08:24:00: burp[19204] in do_backup_server
2017-03-27 08:24:00: burp[19204] Using librsync hash md4
2017-03-27 08:24:00: burp[19204] Logging to /home/backup/nomasrv1exchlogs/0000003 2017-03-27 08:24:00/log
2017-03-27 08:25:10: burp[19204] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:25:10: burp[19204] main socket: SSL write problem in asfd_do_write_ssl: 5 - 32=Broken pipe
2017-03-27 08:25:10: burp[19204] WARNING: shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
2017-03-27 08:25:10: burp[19204] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:25:10: burp[19204] main socket: SSL write problem in asfd_do_write_ssl: 5 - 32=Broken pipe
2017-03-27 08:25:10: burp[19204] /usr/share/burp/scripts/notify_script returned: 0
2017-03-27 08:25:10: burp[19204] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:25:10: burp[19204] main socket: SSL read problem in asfd_do_read_ssl: 5 - 0=Success
2017-03-27 08:25:10: burp[19204] exit child

The process is exited after this.

**Comment by grke** [comment] 2017-03-27 06:44
Hello,
Thanks for the kind words.

In the logs that you posted directly before this message:

The first error took more than an hour to happen.
The second error took just a bit more than one minute, and you probably ran the server whilst stood inside the previous working directory that it deleted (the getcwd warning message).

Is the first error just noise?
Is the second (quick) error the one that you are interested in fixing? I mean, does the error normally happen quickly?

**Comment by remcoluit** [comment] 2017-03-27 06:57
Ah, i see the log is a bit misleading since there was an automated backup at 7:50. When i start the backup everything seems ok and it is receiving data (i see that with iftop). After a while it quits and the the server process is also exited from foreground mode. As you can see this all happens within 5 minutes.
Let me attach the whole logging again:

CLIENT:
c:\Program Files\Burp\bin>burp -a b -c "c:\Program Files\Burp\burpexchlogs.conf"

2017-03-27 08:50:26: burp[12404] c:\Program Files\Burp\burpexchlogs.conf: status
_port unset
2017-03-27 08:50:27: burp[12404] auth ok
2017-03-27 08:50:27: burp[12404] Server version: 2.0.54
2017-03-27 08:50:27: burp[12404] nocsr ok
2017-03-27 08:50:27: burp[12404] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384
TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

2017-03-27 08:50:27: burp[12404] extra_comms_begin ok:autoupgrade:incexc:orig_cl
ient:uname:counters_json:msg:csetproto:
2017-03-27 08:50:27: burp[12404] Server has protocol=0 (auto)
2017-03-27 08:50:27: burp[12404] Using protocol=1
2017-03-27 08:50:27: burp[12404] Compression level: 9
2017-03-27 08:50:27: burp[12404] do backup client
2017-03-27 08:50:27: burp[12404] Using librsync hash md4
2017-03-27 08:50:27: burp[12404] Control handler registered.
Generate VSS snapshots.
Driver="VSS Vista", Drive(s)="D"
2017-03-27 08:51:01: burp[12404] VSS drive letters: 0
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "Task Scheduler
Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "VSS Metadata St
ore Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "Performance Cou
nters Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "ASR Writer", St
ate: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "System Writer",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "SqlServerWriter
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "FSRM Writer", S
tate: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "FRS Writer", St
ate: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "Microsoft Excha
nge Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "NPS VSS Writer"
, State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "WMI Writer", St
ate: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "Registry Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "IIS Config Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "IIS Metabase Wr
iter", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "TS Gateway Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "Certificate Aut
hority", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "COM+ REGDB Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "Dhcp Jet Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "Shadow Copy Opt
imization Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "MSSearch Servic
e Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] VSS Writer (PrepareForBackup): "NTDS", State: 0
x1 (VSS_WS_STABLE)
2017-03-27 08:51:01: burp[12404] Phase 1 begin (file system scan)

ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 64
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 128
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 192
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 256
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 320
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 384
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 448
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 512
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 576
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 640
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 704
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 768
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 832
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 896
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 960
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1024
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1088
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1152
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1216
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 1280
ffffffffffffffffffffffffffffff 1310

2017-03-27 08:51:03: burp[12404] Phase 1 end (file system scan)
2017-03-27 08:51:03: burp[12404] Phase 2 begin (send backup data)

zzzfffffffffffffffffffffffffffffff2017-03-27 08:53:27: burp[12404] main socket:
Got SSL_ERROR_SYSCALL
2017-03-27 08:53:27: burp[12404] main socket: SSL write problem in asfd_do_write
_ssl: 5 - 0=No error
2017-03-27 08:53:27: burp[12404] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:53:27: burp[12404] main socket: SSL read problem in asfd_do_read_s
sl: 5 - 0=No error
 34

--------------------------------------------------------------------------------

Start time: 2017-03-27 08:50:26
  End time: 2017-03-27 08:53:27
Time taken: 03:01
                         New   Changed Duplicate   Deleted     Total |  Scanned
                   ------------------------------------------------------------
             Files:       31         3         0         0        34 |     1310
       Grand total:       34         3         0         0        37 |     1310
                   ------------------------------------------------------------

             Messages:             0
             Warnings:             0

      Bytes estimated:    2786596260 (2.60 GB)
      Bytes in backup:      33569828 (32.01 MB)
       Bytes received:         22777 (22.24 KB)
           Bytes sent:      29249375 (27.89 MB)
--------------------------------------------------------------------------------

2017-03-27 08:53:27: burp[12404] Error in phase 2
2017-03-27 08:53:27: burp[12404] Phase 2 end (send file data)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "Task Scheduler Wr
iter", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "VSS Metadata Stor
e Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "Performance Count
ers Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "System Writer", S
tate: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "SqlServerWriter",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "ASR Writer", Stat
e: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "FSRM Writer", Sta
te: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "FRS Writer", Stat
e: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "Shadow Copy Optim
ization Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "MSSearch Service
Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "Registry Writer",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "IIS Config Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "WMI Writer", Stat
e: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "NPS VSS Writer",
State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "Certificate Autho
rity", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "COM+ REGDB Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "Microsoft Exchang
e Writer", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "TS Gateway Writer
", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "NTDS", State: 0x1
 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "Dhcp Jet Writer",
 State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] VSS Writer (BackupComplete): "IIS Metabase Writ
er", State: 0x1 (VSS_WS_STABLE)
2017-03-27 08:53:31: burp[12404] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:53:31: burp[12404] main socket: SSL read problem in asfd_do_read_s
sl: 5 - 0=No error

SERVER: 
2017-03-27 08:50:27: burp[19238] Connect from peer: ::ffff:x.x.x.x:56419
2017-03-27 08:50:27: burp[19238] auth ok for: nomasrv1exchlogs
2017-03-27 08:50:27: burp[19238] Client nomasrv1exchlogs does not want a certificate signed
2017-03-27 08:50:27: burp[19238] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

2017-03-27 08:50:27: burp[19238] Server is using protocol=0 (auto)
2017-03-27 08:50:27: burp[19238] Client supports being sent json counters.
2017-03-27 08:50:27: burp[19238] Client has set protocol=1
2017-03-27 08:50:27: burp[19238] found old working directory: /home/backup/nomasrv1exchlogs/0000003 2017-03-27 08:24:00
2017-03-27 08:50:27: burp[19238] working_dir_recovery_method: delete
2017-03-27 08:50:27: burp[19238] deleting old working directory
2017-03-27 08:50:27: burp[19238] in do_backup_server
2017-03-27 08:50:27: burp[19238] Using librsync hash md4
2017-03-27 08:50:27: burp[19238] Logging to /home/backup/nomasrv1exchlogs/0000003 2017-03-27 08:50:27/log
2017-03-27 08:53:28: burp[19238] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:53:28: burp[19238] main socket: SSL write problem in asfd_do_write_ssl: 5 - 32=Broken pipe
2017-03-27 08:53:28: burp[19238] MESSAGE: Running notify script: nomasrv1exchlogs /home/backup/nomasrv1exchlogs /home/backup/nomasrv1exchlogs/current log backup 0 sendmail -t -f x@x.nl To: x@x.nl From: burp Subject: %b failed: %c %w
2017-03-27 08:53:28: burp[19238] /usr/share/burp/scripts/notify_script returned: 0
2017-03-27 08:53:28: burp[19238] main socket: Got SSL_ERROR_SYSCALL
2017-03-27 08:53:28: burp[19238] main socket: SSL read problem in asfd_do_read_ssl: 5 - 0=Success
2017-03-27 08:53:28: burp[19238] exit child

The log in the working directory is the same as the server output.

**Comment by grke** [comment] 2017-04-01 02:12
Hello,
I also don't know what the problem is. I would either need access to the machines themselves in order to debug it further, or I would need to be able reproduce it myself on my own machines.

**Comment by remcoluit** [comment] 2017-04-03 07:21
I understand and don't think that it will be easily reproducible. I can give you access to the machines if you connect to my computer with Teamviewer or something similar. I will send you my contact details through the contact form on your website.

**Comment by grke** [comment] 2017-04-21 23:29
Closing, as I am currently unable to reproduce. I believe remcoluit now has a non-burp solution to his remote backup.

**Closed by grke** 2017-04-21 23:29 UTC
