### ISSUE TITLE
Log output sometimes misses newlines after WARNING messages

### ISSUE THREAD

**Issue by davidgubler** [grke/burp#598] opened 2017-07-31 08:12 UTC
The log output (on the burp server) of a client backup sometimes misses newlines after WARNING messages. This is annoying because it causes parsing issues with our monitoring check.

~# zcat /var/lib/burp/foo.cust.vshn.net/current/log.gz
[...]
2017-07-31 01:40:56 +0200: burp[19268] WARNING: Path has vanished: /var/www/foo/public_html/data/news.index.de/segments_18m1b2017-07-31 01:40:56 +0200: burp[19268] WARNING: Path has vanished: /var/www/foo/public_html/data/news.index.en/_10wfs.cfs
2017-07-31 01:40:56 +0200: burp[19268] WARNING: Path has vanished: /var/www/foo/public_html/data/news.index.en/_10wfs.sti
[...]
2017-07-31 01:40:56 +0200: burp[19268] WARNING: Path has vanished: /var/www/foo/public_html/data/news.index.en/segments_18wxm2017-07-31 01:41:31 +0200: burp[19268] End phase2 (receive file data)
2017-07-31 01:41:31 +0200: burp[19268] Backup ending - disconnect from client.
[...]

Burp server: 2.1.12-0vshn1+trusty
Burp client: 2.1.12-0vshn1+xenial

[burplog.txt](https://github.com/grke/burp/files/1186800/burplog.txt)

**Comment by grke** [comment] 2017-08-01 11:40
Hello,
Thanks for this.
This bug report appears to be a duplicate of issue #581, so I will copy your output over to there and close this one.

**Closed by grke** 2017-08-01 11:40 UTC
