### ISSUE TITLE
WARNING during restore breaks with a SSL_ERROR server side

### ISSUE THREAD

**Issue by JvdW** [grke/burp#539] opened 2017-03-01 09:15 UTC
Im using burp 2.0.54 both on the server and on the client, CentOS-7.3, rpms for burp are from yopito/burp2 Copr, openssl is version 1.0.1e both on server and client.

Backing up is no problem but today we tested our restore procedure and found a problem. 
Using the following cmd line:
burp -ar -b 1 -d /tmp/restore ends directly with the following error on the client:

> 2017-03-01 10:06:27: burp[17507] WARNING: Unable to set file times /tmp/restore/bin: ERR=No such file or directory

and with the following error on the server:

> 2017-03-01 10:06:27: burp[30493] main socket: Got SSL_ERROR_SYSCALL
> 2017-03-01 10:06:27: burp[30493] main socket: SSL write problem in asfd_do_write_ssl: 5 - 32=Broken pipe

Using a -r /var lets me restore most of var until it encounters some other special file and then the same error.  
I mention special file because the first error is because 'bin' is a link to 'usr/bin' and that hasn't been restored yet. I don't mind the WARNING but it shouldn't break the SSL connection, I don't see the connection here, no pun intended.

**Comment by grke** [comment] 2017-03-02 09:30
Hello,

Thanks for reporting it.

I don't understand the problem fully.

Are you able to tell me a very simple file structure and sequence of steps that would let me reproduce the problem?

For example, if I am backing up the contents of a directory called '/home/graham/testdir', how do I arrange files and symlinks inside that directory in order to experience the issue?

**Comment by JvdW** [comment] 2017-03-02 12:24
On 2-3-2017 10:30, grke wrote:
>
> Hello,
>
> Thanks for reporting it.
>
> I don't understand the problem fully.
>
> Are you able to tell me a very simple file structure and sequence of 
> steps that would let me reproduce the problem?
>
> For example, if I am backing up the contents of a directory called 
> '/home/graham/testdir', how do I arrange files and symlinks inside 
> that directory in order to experience the issue?
>
>
If I specifiy in /etc/burp/clientconfdir/haproxy03 to only include=/bin 
and then to run a backup on haproxy03 and then do:
burp -ar -b 3 -d /tmp/restore
It will stop at creating /tmp/restore/bin with the error in the Issue, I 
figured maybe its /tmp so did mkdir /testing and burp -ar -b 3 -d 
/testing. Same result, see below

This is the output of the various command that I used:

root@haproxy03:~ # burp -ar -b 3 -d /testing
2017-03-02 13:09:03: burp[16925] /etc/burp/burp.conf: status_port unset
2017-03-02 13:09:03: burp[16925] auth ok
2017-03-02 13:09:03: burp[16925] Server version: 2.0.54
2017-03-02 13:09:03: burp[16925] nocsr ok
2017-03-02 13:09:03: burp[16925] SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD

2017-03-02 13:09:03: burp[16925] extra_comms_begin ok:autoupgrade:incexc:orig_client:uname:sincexc:counters_json:msg:csetproto:rshash=blake2:
2017-03-02 13:09:03: burp[16925] Server has protocol=0 (auto)
2017-03-02 13:09:03: burp[16925] Using protocol=1
2017-03-02 13:09:03: burp[16925] doing restore 3:
2017-03-02 13:09:03: burp[16925] doing restore confirmed

2017-03-02 13:09:03: burp[16925] WARNING: Unable to set file times /testing/bin: ERR=No such file or directory
2017-03-02 13:09:03: burp[16925] ret: -1

root@haproxy03:~ # file /bin
/bin: symbolic link to `usr/bin'
root@haproxy03:~ # ls -lZ /bin
lrwxrwxrwx. root root system_u:object_r:bin_t:s0       /bin -> usr/bin
root@haproxy03:~ #

Server side message in /var/log/messages:
Mar  2 13:15:19 bkpsrv burp[32019]: forked child: 27697
Mar  2 13:15:19 bkpsrv burp[27697]: auth ok for: haproxy03
Mar  2 13:15:19 bkpsrv burp[27697]: Client haproxy03 does not want a certificate signed
Mar  2 13:15:19 bkpsrv burp[27697]: SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD#012
Mar  2 13:15:19 bkpsrv burp[27697]: Server is using protocol=0 (auto)
Mar  2 13:15:19 bkpsrv burp[27697]: Client supports being sent json counters.
Mar  2 13:15:19 bkpsrv burp[27697]: Client has set protocol=1
Mar  2 13:15:19 bkpsrv burp[27697]: in do_restore
Mar  2 13:15:19 bkpsrv burp[27697]: Logging to /volumes/backup2/burp_data/haproxy03/0000003 2017-03-02 13:06:59/restorelog
Mar  2 13:15:21 bkpsrv burp[27697]: Compressing /volumes/backup2/burp_data/haproxy03/0000003 2017-03-02 13:06:59/restorelog to /volumes/backup2/burp_data/haproxy03/0000003 2017-03-02 13:06:59/restorelog.gz...
Mar  2 13:15:21 bkpsrv burp[27697]: WARNING: Path exists: /testing/bin
Mar  2 13:15:21 bkpsrv burp[27697]: WARNING: Unable to set file times /testing/bin: ERR=No such file or directory
Mar  2 13:15:21 bkpsrv burp[27697]: main socket: Peer closed SSL session

Message from syslogd@bkpsrv at Mar  2 13:15:21 ...
  error:140D00CF:SSL routines:SSL_write:protocol is shutdown:ssl_lib.c:999:
Mar  2 13:15:21 bkpsrv burp[27697]: main socket: SSL write problem in asfd_do_write_ssl: 1 - 0=Success
Mar  2 13:15:21 bkpsrv error:140D00CF:SSL routines:SSL_write:protocol is shutdown:ssl_lib.c:999:
Mar  2 13:15:21 bkpsrv burp[27697]: MESSAGE: Running notify script: haproxy03 /volumes/backup2/burp_data/haproxy03 /volumes/backup2/burp_data/haproxy03/0000003 2017-03-02 13:06:59 restorelog restore 0 sendmail -t To: MY@COM From:

Message from syslogd@bkpsrv at Mar  2 13:15:21 ...
  error:140D00CF:SSL routines:SSL_write:protocol is shutdown:ssl_lib.c:999:
Mar  2 13:15:21 bkpsrv burp[27697]: main socket: SSL write problem in asfd_do_write_ssl: 1 - 0=Success
Mar  2 13:15:21 bkpsrv error:140D00CF:SSL routines:SSL_write:protocol is shutdown:ssl_lib.c:999:
Mar  2 13:15:21 bkpsrv burp[27697]: MESSAGE:  burp Subject: %b failed: %c %w
Mar  2 13:15:21 bkpsrv burp[27697]: /etc/burp/notify_script returned: 0
Mar  2 13:15:21 bkpsrv burp[27697]: main socket: Peer closed SSL session
Mar  2 13:15:21 bkpsrv burp[27697]: exit child
Mar  2 13:15:21 bkpsrv burp[32019]: pipe from child: end of data
Mar  2 13:15:21 bkpsrv burp[32019]: pipe from child: disconnected fd 7

Edited for privacy reasons :-)
SELinux is in Permissive mode!

Joop

**Comment by grke** [comment] 2017-03-08 06:24
Thanks for that, I will see if I can reproduce the problem with this information.

**Comment by grke** [comment] 2017-03-26 09:00
I was unable to reproduce this on debian, so I installed centos 7.3 in a VM. I can now reproduce the problem.

It happens after restoring metadata on a symlink. Maybe it shouldn't try to set the file times at this point.
You will find that the restore isn't interrupted and will get to the end if you comment out this in
src/client/protocol1/restore.c:

                      if(attribs_set_file_times(asfd, fname,
                              &sb->statp, cntr))
                                        return -1;

This isn't the proper fix though, I will need to think about it.

Next, I will see if I can reproduce it on debian by setting up a symlink with metadata.

**Comment by puzzle-it-nu** [comment] 2017-03-26 09:11
On 26-3-2017 11:00, grke wrote:
>
> I was unable to reproduce this on debian, so I installed centos 7.3 in
> a VM. I can now reproduce the problem.
>
> It happens after restoring metadata on a symlink. Maybe it shouldn't
> try to set the file times at this point.
> You will find that the restore isn't interrupted and will get to the
> end if you comment out this in
> src/client/protocol1/restore.c:
>
> |if(attribs_set_file_times(asfd, fname, &sb->statp, cntr)) return -1; |
>
> This isn't the proper fix though, I will need to think about it.
>
> Next, I will see if I can reproduce it on debian by setting up a
> symlink with metadata.
>
>
I'm not totally sure but I use restore quite often and never had this
problem so either I have been able to miss this case or something
changed in that part of the code recently, probably being the former.

Thanks for looking into it,

Joop

**Comment by grke** [comment] 2017-03-27 06:07
The problem is that I should use lutimes() instead of utime() to set the times. The former doesn't deference symlinks.
Fix coming up.

**Comment by grke** [comment] 2017-03-27 08:22
There is a fix in master now, and will be in the next release.

**Closed by grke** 2017-03-27 08:22 UTC
