### ISSUE TITLE
How to debug and send a trace (2.0.48 segfault?)

### ISSUE THREAD

**Issue by kellogs** [grke/burp#498] opened 2016-10-25 06:01 UTC
Hello,

I ran burp 2.048 on two Debian GNU/Linux systesm (server/client) and yet in protocole 1 there was a segmentation fault on client side after hours.
burp -a b
Erreur de segmentation

Settings: encryption turned on client side. Nothing particular except protocol 1. I was doing a backup of /home.

How can I debug and send a trace? I probably can use gdb, what would be most useful for you? I probably need to recompile from git also. Are there guidelines for debuging? 

Kind regards,
Kellogs

**Comment by grke** [comment] 2016-10-25 11:33
Hello,

I am very interested in segfaults in 2.0.48.
To get a backtrace:

gdb --args burp -a b

Enter 'run'. 
Wait for the segfault.
Enter 'bt'.
Copy the output here.

Once I can reproduce a segfault, I will fix it quickly.
Even more so with 2.0.48, as that was intended to be my 'stable' release.

**Comment by grke** [comment] 2016-11-08 11:25
Closing. If you manage to get a stacktrace, please reopen.

**Closed by grke** 2016-11-08 11:25 UTC
