### ISSUE TITLE
librsync on RHEL 7

### ISSUE THREAD

**Issue by htbase** [grke/burp#294] opened 2015-06-15 20:22 UTC
We are trying to install Burp on RHEL 7 and it keeps saying that librsync is not installed but when we issue the rpm -q command, we see the following:

[root@localhost /]# rpm -q librsync
librsync-1.0.0-1.el5.x86_64

When we run ./configure, we keep hitting this message:

checking librsync.h usability... no
checking librsync.h presence... no
checking for librsync.h... no
checking for rs_delta_begin in -lrsync... no
Please install librsync

Any ideas on how to work this out?

Thanks

**Comment by tokudan** [comment] 2015-06-15 21:44
Try installing the matching librsync-devel package.

**Comment by htbase** [comment] 2015-06-16 03:23
Thanks

Installed but I get the following when running make:

g++   -c  -fno-strict-aliasing -fno-exceptions -fno-rtti -Wall  -I. -I..  -g -O2  auth.c
In file included from ../protocol1/rs_buf.h:29:0,
                 from ../protocol1/include.h:8,
                 from ../protocol1/sbuf_protocol1.h:4,
                 from ../sbuf.h:8,
                 from ../include.h:28,
                 from include.h:4,
                 from auth.c:1:
../librsync.h:55:13: error: expected initializer before ‘_fseeki64’
 int __cdecl _fseeki64(FILE *, __int64, int);
             ^
../librsync.h:56:1: error: ‘__int64’ does not name a type
 __int64 __cdecl _ftelli64(FILE *);

Any ideas?

Thanks again

**Comment by grke** [comment] 2015-06-16 12:15
Hello,
I think that either the burp code is missing a header declaration, or you don't have all the correct headers installed.
To figure out which, I would suggest downloading the librsync source and running './configure && make' inside it. If librsync compiles, then the problem is within burp, If it doesn't, the problem is elsewhere.

**Comment by laapsaap** [comment] 2015-06-16 12:34
I just compiled it 2.x on CentOS 64bits without any problems.  This was a minimal installation, all I did was adding EPEL repo and installed the libraries using YUM.

**Comment by laapsaap** [comment] 2015-06-17 15:33
Its not librsync package that you need. Its librsync-devel.

Anyways this is the list of files you need to install to build burp on CentOS7.  Mind you, you need EPEL repo for librsync-devel.

        - gcc-c++       
        - libacl-devel  
        - librsync-devel
        - ncurses-devel 
        - openssl-devel

**Comment by grke** [comment] 2015-06-18 20:12
I will be closing this issue in a few days unless there is any more information.

**Closed** 2015-07-20 03:26 UTC
