### ISSUE TITLE
Deleted data files when cleanup occurs while another dedup_group member is backing up

### ISSUE THREAD

**Issue by sberthelot** [grke/burp#424] opened 2016-04-26 16:48 UTC
In protocol 2 we have got only the first keep value honored for backups.
We use usually :
```
keep=30
keep=12
```
and now we get only 31 (1 more than expected) backups kept in proto 2

I wonder whether hardlinked flag (not meaningful in proto 2) changes the calculation for deleting old backups...

I found this while investigating other problems like :
```
2016-04-26 11:19:16: burp[29509] Restore settings:
2016-04-26 11:19:16: burp[29509] backup = '0'
2016-04-26 11:19:16: burp[29509] include = '/'
2016-04-26 11:19:16: burp[29509] include = '/var/backup/mysql'
2016-04-26 11:19:16: burp[29509] include = '/var/backup/pgsql'
2016-04-26 11:19:16: burp[29509] swap 0 to: /var/backup/burp/slackware1401/data/0000/0000/2598
2016-04-26 11:19:16: burp[29509] swap 1 to: /var/backup/burp/slackware1401/data/0000/0000/0EFA
2016-04-26 11:19:16: burp[29509] could not open /var/backup/burp/slackware1401/data/0000/0000/0EFA: No such file or directory
2016-04-26 11:19:16: burp[29509] Could not retrieve blk data.
```

Is there any way to find why/when this file was deleted using bsigs and manifest/dindex files ? (I suspect another bug since this file has been deleted automatically)

**Comment by grke** [comment] 2016-04-26 21:21
Hello,

I think that multiple 'keep' values are fixed in current git master, ready for the next release in a few days  time: https://github.com/grke/burp/issues/417

I don't know what the problem is with the missing data file.
If you look at /var/backup/burp/slackware1401/data/cc.log, maybe you can at least find a line saying when it was deleted.

**Comment by sberthelot** [comment] 2016-04-27 07:56
Thanks a lot for your answer.
I didn't see the previous resolved  issue, sorry, so I'll test the current git version for the fix (we still got regexp problems with restore which seems to be fixed recently also)

I think I found the problem for our deleted data files looking at the log file you mentioned

```
2016-04-03 01:13:20: burp[30210] Attempting to clean up unused data files /var/backup/burp/slackware1401/clients
2016-04-03 01:13:20: burp[30210] /var/backup/burp/slackware1401/clients/client12.emisfr.net looks like it has a backup in progress.
2016-04-03 01:13:20: burp[30210] Give up clean up attempt.
2016-04-03 01:13:20: burp[30210] Deleted 0000/0000/000B
[*many* *many* more Deleted lines]
```

From what I understand `static int get_dfiles_to_merge(...)` function tests for `backup_in_progress` but returns 0 (`ret=0`) though it has not populated the strlist.
First `if` in `delete_unused_data_files` then doesn't get to `goto end` as it should if I understand correctly.

I can prepare a pull request for this change but I'm not sure if it should be done this way and I would only change `ret=0` by `ret=1` in `get_dfiles_to_merge` in the `switch(backup_in_progress(fullpath))` statement.

**Comment by grke** [comment] 2016-04-27 10:20
Thanks a lot for that, I agree with your assessment.
I am preparing a patch now. It is a little bit more than just changing ret=0 to 1.

**Comment by grke** [comment] 2016-04-28 11:54
There is now a fix for this in master, for the next release, and some more tests for it too.

**Closed by grke** 2016-04-28 11:54 UTC
