### ISSUE TITLE
Burp 2 status monitor should detect from storage with protocol=0

### ISSUE THREAD

**Issue by ziirish** [grke/burp#410] opened 2016-03-21 16:46 UTC
Hello,

I am using Burp `2.0.34` and it seems the status monitor is not able to handle both protocol 1 and 2 at the same time.

```
root@titanium:~# grep "^protocol" /etc/burp/burp.conf
root@titanium:~# burp -a m
{ "logline": "auth ok" }
{ "logline": "Server version: 2.0.34" }
{ "logline": "nocsr ok" }
{ "logline": "SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
" }
{ "logline": "extra_comms_begin ok:autoupgrade:incexc:orig_client:uname:msg:csetproto:rshash=blake2:" }
{ "logline": "Server has protocol=0 (auto)" }
{ "logline": "Using protocol=2" }
{ "logline": "in monitor" }
c:
{
    "clients": [
        {
            "name": "agent",
            "labels": [
                "color: #123"
            ],  
            "run_status": "idle",
            "backups": [

            ]
        },  
        {
            "name": "test1",
            "labels": [
                "color: black"
            ],  
            "run_status": "idle",
            "backups": [

            ]
        },
        {
            "name": "testclient",
            "labels": [
                "color: #123"
            ],   
            "run_status": "idle",
            "backups": [
                {
                    "number": 1,
                    "timestamp": 1458053811,
                    "flags": [
                        "deletable",
                        "current",
                        "manifest"
                    ],
                    "logs": {
                        "list": [
                            "backup",
                            "backup_stats"
                        ]
                    }
                }
            ]
        }
    ]
}
{ "logline": "stdin: end of data" }
{ "logline": "Exiting main loop" }
```

Now when I force protocol 1 for the client used to open the status monitor channel I got:

```
root@titanium:~# grep "^protocol" /etc/burp/burp.conf 
protocol = 1
root@titanium:~# burp -a m
{ "logline": "auth ok" }
{ "logline": "Server version: 2.0.34" }
{ "logline": "nocsr ok" }
{ "logline": "SSL is using cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
" }
{ "logline": "extra_comms_begin ok:autoupgrade:incexc:orig_client:uname:msg:csetproto:rshash=blake2:" }
{ "logline": "Using protocol=1" }
{ "logline": "in monitor" }
c:
{
    "clients": [
        {
            "name": "agent",
            "labels": [
                "color: #123"
            ],  
            "run_status": "idle",
            "backups": [

            ]
        },  
        {
            "name": "test1",
            "labels": [
                "color: black"
            ],
            "run_status": "idle",
            "backups": [
                {
                    "number": 2,
                    "timestamp": 1458136428,
                    "flags": [
                        "hardlinked",
                        "deletable",
                        "current",
                        "manifest"
                    ],
                    "logs": {
                        "list": [
                            "backup",
                            "backup_stats"
                        ]
                    }
                }
            ]
        },
        {
            "name": "testclient",
            "labels": [
                "color: #123"
            ],
            "run_status": "idle",
            "backups": [

            ]
        }
    ]
}
{ "logline": "stdin: end of data" }
{ "logline": "Exiting main loop" }
```

I understand the fix is probably not trivial as the storage has changed between protocol 1 and 2 but I think the monitor should be able to handle both.

In this case, it would be great to also know what protocol a client uses.

The problem is what to do when one switched the protocol between two backups?

**Comment by grke** [comment] 2016-03-22 07:42
Hello,

I think the problem is probably this:

The server is configured to have 'protocol=0', and so it doesn't actually know what protocol will be in
use by any particular client until that client connects to it.

So if you are listing clients that are not your current client, it will look for protocol2 backups.

To prove this is true (or as a workaround), you can configure protocol=1 and protocol=2 as appropriate in the server clientconfdir files. You should find that you are able to force it to have the correct output for each client.


A better fix:
I think the server could do a better job of detecting backups of which protocol a client actually has, and using those.
For example, if there are protocol1 backups, and no protocol2 backups, use the protocol1 backups, and vice versa. If there are both kinds of backups, use the one which has the most recent backup because that is the best guess for the protocol that is currently in use.



I don't think it would be a good idea to try to show both sets of backups for one client simultaneously.
You can't for example, do a 'burp -a l' for both protocols simultaneously, you have to configure which protocol the client is going to use first. Trying to implement such a thing would be a big mess. For example, the configuration might be broken for the non-active protocol's backups.

**Comment by ziirish** [comment] 2016-03-22 11:28
Thanks for the quick answer.

Your workaround works as expected. It's good enough for me.

I think we can close this issue unless you want to implement the improvements you were talking about?

**Comment by grke** [comment] 2016-03-22 12:25
I have just been trying to fix it. I didn't succeed yet, so keep it open and I will try again another day. Thanks for the report.

**Comment by grke** [comment] 2017-12-24 07:43
Finally got round to doing this, now in master.

**Closed by grke** 2017-12-24 07:43 UTC
Labels: Bug
