### ISSUE TITLE
Possibile improvements

### ISSUE THREAD

**Issue by bojleros** [grke/burp#834] opened 2019-11-20 08:03 UTC
Hi,

Please allow me to share some ideas that comes from my recent Burp tests and experience of running Bareos. I believe it can be beneficial for Burp.

***Background***

Since some of my machines are running on low TDP integrated cpu's backup performance became problematic as soon as compression or encryption is switched on. In fact compression can be skipped but it is not a case for encryption nowadays. This is how i found bareos-fd (18.2.5) to be single-threaded and completely too slow on some of my hosts. I like their feature called TLS-PSK but i have found no way to gain more performance f.e. by choosing weaker encryption schema , or by selectively disabling TLS on slower clients. Apart of that i believe that Bareos still inherits most of problems described under https://burp.grke.org/why.html  where the most significant one is related to the fact that there is no strict relation between single backups so restore relies only on timestamps! Apart of that you can find metadata interleaved with data inside of volumes so zfs dedup will just not work.

***Single-threaded backup clients***

As i mentioned above, some of my hosts are not a monsters of performance but they have more than single core. What i have found is that both clients (bareos-fd and burp-client) are not able to use more than single cpu thread while taking a backup. This is how i ended up in having a speedup by setting `ssl_compression = zlib0`. As far as i understand burp protocol v2 will bring some interesting but also cpu consuming features. Perhaps it would be good to consider having more parallelism here?

***Network throughput scaling***

Some of my machines have strong enough cpu to saturate 1Gbit links. As far as i know there is no free open source backup system capable of spreading backup/restore job streams into multiple tcp connections. Having such ability allows efficient lacp bonding usage and network bandwidth scaling however i do not consider it a problem because of how librsync works.

Regards,
Bart

**Comment by grke** [comment] 2019-11-23 01:30
Hello,

Thanks for taking the time to explain your ideas to me.

or both the threaded and the throughput ideas, I think it would require such a refactor of burp from the ground up, you are probably really talking about re-implementing something completely new.

However, I will keep this feature request open for now, so that I might think about it some more in the background.

**Comment by bojleros** [comment] 2019-11-23 07:50
Hi,

> or both the threaded and the throughput ideas, I think it would require such a refactor of burp from the ground up, you are probably really talking about re-implementing something completely new.

It depends f.e. there should be two major factors that generate cpu load: compression, encryption. Why not separate this two (heaviest) workloads into a dedicated threads and leave remaining workload in a main worker thread?

I also forgot another two remarks:

***Inodes and scaling***

Have a look at /var/spool/burp on burp-server. If you count files in each subdir separately you will find that the number of files will be equal or greater to he number of files that was actually backed up. Now consider clients that generate a tons of new small files multiplied by count of that clients. This is how the backup volume performance will likely decrease due to high inode count. (That's why i abandoned my first backup script based on rsync ;) )


***Sophisticated backup schemas***

The problem is that i can have host running database. So basically i need to backup OS files and database separately since db volume is too big to take a full backup each time we run the job. Is it part of design that such setups would require having a separate client config files? (I do not consider filesystem db dump as a right way of doing backup)

***Offsite backup***

s3?


PS.
Most of free backup solutions have known limitations and conservative approach. That's why i find your manifesto (https://burp.grke.org/why.html) to be very positive.

**Comment by grke** [comment] 2019-11-26 21:29
Re: threads
I understand what you mean. However, my point is that burp currently does not use threads, and it's architecture is not designed with threads in mind, or the processing of files in parallel, with associated client/server comms in mind. Therefore, it is not simple just to add a new thread for encryption, and a new thread for compression, and parallel comms  - although, I am willing to be proven wrong if you would like to show me how. Maybe the problem is that I don't have much experience with threads.

Re: inodes:
This is the one of the reasons that I made burp protocol 2 - it solves the problem of too many inodes.

**Comment by bojleros** [comment] 2019-12-02 19:11
Hi,

Thank you for encouragement. It would be great do help however my C skills was DSP/Embedded oriented and now are almost gone (change of profession). This is why i decided to share ideas. I hope you do not find them to be too nosy and intrusive.

**Comment by grke** [comment] 2020-01-01 02:20
Thank you for your ideas and positive attitude, it is appreciated.
I have thought about your ideas more this month.

As I mentioned before, I still believe you are really talking about re-implementing something almost completely new that would be a complete a refactor, so I am not going to do these things in burp.

They would be good for a new project, but I have no time to do that.
So, I am closing this, with apologies.
Thanks again.

**Closed by grke** 2020-01-01 02:20 UTC
