### ISSUE TITLE
After upgrading server: could not start signature job. (error in backup phase 2)

### ISSUE THREAD

**Issue by do11** [grke/burp#555] opened 2017-04-05 18:11 UTC
After upgrading server from 1.4.40 (centos 6's + burp 1.4.40 from EPEL) to burp 2.1.6, all next backup (from centos 6 + burp 1.4.40 from EPEL) runs fail with such error:

```
0000036 2017-04-05 21:00:01

/home/burp/ns2/working/log:

2017-04-05 21:00:02: burp[32019] Client version: 1.4.40
2017-04-05 21:00:02: burp[32019] Protocol: 1
2017-04-05 21:00:02: burp[32019] WARNING: Client 'ns2' version '1.4.40' does not match server version '2.1.6'. An upgrade is recommended.
2017-04-05 21:00:02: burp[32019] Begin phase1 (file system scan)
2017-04-05 21:00:04: burp[32019] End phase1 (file system scan)
2017-04-05 21:00:04: burp[32019] Begin phase2 (receive file data)
2017-04-05 21:00:05: burp[32019] could not start signature job.
2017-04-05 21:00:15: burp[32019] End phase2 (receive file data)
2017-04-05 21:00:15: burp[32019] error in backup phase 2
```

As I understood before, upgrading server version above clients is supposed to be supported.

Btw, what is signature job? It seems not SSL certs related, since its phase 2 already.

**Comment by do11** [comment] 2017-04-05 18:32
Googling shows that this is something librsync related. For server to be inter-operable with burp-1.4.40 clients, what highest version should it run, if not 2.1.6? Maybe 2.0.54 or, after all, downgrade to 1.4.40?

**Comment by grke** [comment] 2017-04-05 23:36
Hello,
The message 'could not start signature job' most likely means that there is a problem with librsync on your server.
Here is the code from burp's src/server/protocol1/backup_phase2.c:

```
        blocklen=get_librsync_block_len(cb->endfile.buf);
        if(!(p1b->protocol1->sigjob=
#ifdef RS_DEFAULT_STRONG_LEN
                rs_sig_begin(blocklen, RS_DEFAULT_STRONG_LEN)
#else
                // This is for librsync-1.0.0. RS_DEFAULT_STRONG_LEN was 8 in
                // librsync-0.9.7.
                rs_sig_begin(blocklen, 8,
                  rshash_to_magic_number(get_e_rshash(cconfs[OPT_RSHASH])))
#endif
        ))
        {
                logp("could not start signature job.\n");
                goto end;
        }
```

This is code that only runs on the server side and has nothing to do with client version.
The rs_sig_begin() part is a call to librsync.

**Comment by do11** [comment] 2017-04-05 23:55
ic. Thanks. I currently downgraded everything to 1.4.40 (package from epel) to continue daily operations working. Maybe, when I get more time I will experiment more. But, really, this is usual centos 6, with `librsync-1.0.0-1.el6.x86_64` from it, which was working good with `burp-server-1.4.40-1.el6.x86_64`. So, I don't really know what to try next.

**Comment by grke** [comment] 2017-04-05 23:59
Hello,

When I have time (I have just got back from a short holiday to find lots of emails and real life stuff to deal with), I will try to install what you have and see if I can reproduce it.

It is worth noting that I don't produce these EPEL packages you are using, so if it is a problem with packaging, I won't be able to fix it for you.

**Comment by grke** [comment] 2017-04-06 00:16
Are you just backing up '/', or something more complicated?

**Comment by do11** [comment] 2017-04-06 09:45
Config from `ns2` from first post:

```
mode = client
port = 4971
server = 19x.16x.1x.6x
password = xxxxxxxx
cname = ns2
pidfile = /var/run/burp.client.pid
syslog = 0
stdout = 0
progress_counter = 1
server_can_restore = 0
cross_filesystem=/home
cross_all_filesystems=0
ca_burp_ca = /usr/sbin/burp_ca
ca_csr_dir = /etc/burp/CA-client
ssl_cert_ca = /etc/burp/ssl_cert_ca.pem
ssl_cert = /etc/burp/ssl_cert-client.pem
ssl_key = /etc/burp/ssl_cert-client.key
ssl_peer_cn = burpserver
include = /
exclude_fs = sysfs
exclude_fs = tmpfs
exclude_fs = proc
exclude_fs = devpts
exclude_fs = devtmpfs
nobackup = .nobackup
exclude_comp=bz2
exclude_comp=gz
```

It is centos 6.8 with `burp-client-1.4.40-1.el6.x86_64` (from [epel](https://dl.fedoraproject.org/pub/epel/6/)). It was working good (1.4.40 client to 1.4.40 server) before upgrading server to 2.1.6.

**Comment by grke** [comment] 2017-04-17 02:36
Hello,

I spent all day installing centos 6.9 and attempting to install freebsd-9.1.

I had problems with freebsd because its ports system complains that this version of freebsd is too old.
Eventually, I gave up on that.

Since this particular issue ("could not start signature job") is only a problem on the server side anyway,
I just connected with a debian client instead.

So, with server centos-9.1, and burp 2.1.6 installed from https://copr.fedorainfracloud.org/coprs/yopito/burp2-latest/ and epel from http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-9.noarch.rpm - I get these packages:

[root@centos clientconfdir]# rpm -qa|grep burp
burp2-client-2.1.6-1.el6.x86_64
burp2-server-2.1.6-1.el6.x86_64
[root@centos clientconfdir]# rpm -qa|grep librsync
librsync-1.0.0-1.el6.x86_64

And it is able to start signature jobs fine.

I think that your problem was probably something to do with your librsync not being the version of
librsync that the burp package was compiled for. I know that you wrote that you have librsync-1.0.0-1
too. However, it works fine for me.
I don't think I can help any further with this, so I am closing this issue.

**Closed by grke** 2017-04-17 02:36 UTC
