### ISSUE TITLE
2.0.21 key generation fails on first time connect

### ISSUE THREAD

**Issue by laapsaap** [grke/burp#307] opened 2015-07-13 13:04 UTC
I am not sure what is going wrong here, but it worked in 1.4 and 2.0.20.  When I connect a client for the first time to the server ssl_cert-client.pem & ssl_cert_ca.pem stays empty.

```
42831:error:0906D06C:PEM routines:PEM_read_bio:no start line:/SourceCache/OpenSSL098/OpenSSL098-52.10.1/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE
42831:error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib:/SourceCache/OpenSSL098/OpenSSL098-52.10.1/src/ssl/ssl_rsa.c:729:
2015-07-13 15:01:28: burp[42831] error initialising ssl ctx
```

Normally I just remove all the ssl_ files and user.csr on the client side and the user files in /CA on the server side and reconnect. Then everything will be auto-generated.

```
2015-07-13 15:02:44: burp[42883] Could not find ssl_cert /etc/burp/ssl_cert-client.pem: No such file or directory
2015-07-13 15:02:44: burp[42883] Could not find ssl_key /etc/burp/ssl_cert-client.key: No such file or directory
2015-07-13 15:02:44: burp[42883] Could not find ssl_cert_ca /etc/burp/ssl_cert_ca.pem: No such file or directory
2015-07-13 15:02:44: burp[42883] auth ok
2015-07-13 15:02:44: burp[42883] Server version: 2.0.21
2015-07-13 15:02:44: burp[42883] Server will sign a certificate request
2015-07-13 15:02:44: burp[42883] Generating SSL key and certificate signing request
2015-07-13 15:02:44: burp[42883] Running '/usr/sbin/burp_ca --key --keypath /etc/burp/ssl_cert-client.key --request --requestpath /etc/burp/CA-client/user.csr --name user'
generating key user: /etc/burp/ssl_cert-client.key
Generating RSA private key, 2048 bit long modulus
...........+++
..+++
e is 65537 (0x10001)
generating request user
2015-07-13 15:02:44: burp[42883] /usr/sbin/burp_ca returned: 0
2015-07-13 15:02:44: burp[42883] Sent /etc/burp/CA-client/user.csr
2015-07-13 15:02:44: burp[42883] main socket: Peer closed SSL session
2015-07-13 15:02:44: burp[42883] transfer file returning: -1
2015-07-13 15:02:44: burp[42883] Received: /etc/burp/ssl_cert-client.pem.42883
2015-07-13 15:02:44: burp[42883] main socket: Peer closed SSL session
2015-07-13 15:02:44: burp[42883] transfer file returning: -1
2015-07-13 15:02:44: burp[42883] Received: /etc/burp/ssl_cert_ca.pem.42883
2015-07-13 15:02:44: burp[42883] Rewriting conf file: /etc/burp/burp.conf
2015-07-13 15:02:44: burp[42883] Re-opening connection to server
2015-07-13 15:02:49: burp[42883] Can't read ssl_cert: /etc/burp/ssl_cert-client.pem
42883:error:0906D06C:PEM routines:PEM_read_bio:no start line:/SourceCache/OpenSSL098/OpenSSL098-52.10.1/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE
42883:error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib:/SourceCache/OpenSSL098/OpenSSL098-52.10.1/src/ssl/ssl_rsa.c:729:
2015-07-13 15:02:49: burp[42883] error initialising ssl ctx
```

This is happening after I updated from 2.0.20 to 2.0.21.

**Comment by laapsaap** [comment] 2015-07-13 13:55
```
 # burp_ca --name user --ca backup_CA --key --request --sign --batch
generating key user: /etc/burp/CA/user.key
Generating RSA private key, 2048 bit long modulus
.........................................................................................................................................................................+++
.+++
e is 65537 (0x10001)
generating request user
Using configuration from /etc/burp/CA.cnf
wrong number of fields on line 170 (looking for field 6, got 1, '' left)
```

**Comment by grke** [comment] 2015-07-14 11:50
2.0.21 could refer to many different commits on the 2.0.21 branch.
Specifically which commit are you testing here, and what are the operating systems involved?

If you have the source code on the server, try this:
make clean
cd test && make test
This will build and run a test server, and a test client will connect to it and do the certificate
exchange and sequences of test backups/verifies/restores.

**Comment by laapsaap** [comment] 2015-07-14 14:38
latest commit 2.0.21 as of speaking.  I run burp server on CentOS6, clients on Ubuntu 14.04 and Mac 10.10.3.

on CentOS7 compilation and test are succesfull, but on Ubuntu 14.04 it fails.

```
Initialising server certificate authority

Starting test server

Running burp1 tests

Test 1
Interrupt server phase1

Test 1 failed: /home/alexl/Tmp/burp/test/target/var/spool/burp/testclient/working is not a symlink 

Killing test server
./test_main: line 79: kill: (4533) - No such process
```

**Comment by grke** [comment] 2015-07-14 20:04
Which commit are you testing?

**Comment by laapsaap** [comment] 2015-07-15 13:27
00e203d11e413088f82158054a9e10a529e5535a

**Comment by grke** [comment] 2015-07-18 05:39
On the client that failed, do you end up with:

/etc/burp/ssl_cert-client.pem.(pid)
/etc/burp/ssl_cert_ca.pem.(pid)

instead of

/etc/burp/ssl_cert-client.pem
/etc/burp/ssl_cert_ca.pem

?

If you are doing the exchange with the client as a non-root user, does it work if you run it as root?

**Comment by laapsaap** [comment] 2015-07-20 10:03
I run the client as root user.

in /etc/burp (client)
----------   1 root root     0 Jan  1  1970 ssl_cert_ca.pem
-rw-------   1 root root  1675 Jul 20 12:00 ssl_cert-client.key
----------   1 root root     0 Jan  1  1970 ssl_cert-client.pem

:/etc/burp/CA-client$ ls -la
-rw-r--r-- 1 root root 924 Jul 20 12:00 peter.csr

and on the server side in /etc/burp/CA  no peter.csr and peter.crt is being created.


How i solve it right now is creating the files manually, but its quite an hassle for new users.

**Comment by grke** [comment] 2015-07-20 11:33
Hello, in the last couple of weeks, I have set up a system that runs automatic tests in Amazon cloud every time I commit a change to my local git. The two test machines are Ubuntu 14.04 and Windows 2012. Ubuntu 14.04 runs 'make test' successfully, which involves exchanging certificates with itself.
So I don't know what the problem is either.
I notice in the output above that something is mentioning openssl-0.9.8. That is quite old. Maybe there is some difference between openssl versions that causes this. My ubuntu 14.04 has openssl-1.0.0.

**Comment by laapsaap** [comment] 2015-07-21 14:53
When I run this on the server, I get this

```
# /usr/sbin/burp_ca --name laap --ca adyenbackup_CA --sign --batch --dir /etc/burp/CA --config /etc/burp/CA.cnf
Using configuration from /etc/burp/CA.cnf
wrong number of fields on line 170 (looking for field 6, got 1, '' left)
```

**Comment by grke** [comment] 2015-07-21 20:09
I am currently moving house, so it is not easy for me to check. What does line 170 look like?

Maybe the old openssl is on the centos6 machine.

**Comment by laapsaap** [comment] 2015-07-22 13:38
openssl-devel-1.0.1e-30.el6.11.x86_64
openssl-1.0.1e-30.el6.11.x86_

in burp_ca its an empty line
```
  cat <<-EOF > ${TEMP}
        RANDFILE                = /dev/urandom
        req_extensions          = v3_req

        [ req ]
        distinguished_name      = req_distinguished_name
        prompt                  = no

        [ v3_req ]
        basicConstraints=CA:false
        $altname

        [ req_distinguished_name ]
        commonName                      = ${name}
LINE 170
EOF
```

I know its openssl error msg and the burp tests succeeded on the centos 6 backup server. So I was thinking maybe its a configuration problem. I removed /etc/burp and started over again, using http://burp.grke.org/docs/burp_ca.html as a guide.  But same problem.

I will test it out today again with new servers and new environment.

**Comment by laapsaap** [comment] 2015-07-22 14:16
I tested everything and I can conclude;

* its not the client
* it doesnt happen on new installation on the same server
* its not CA.cnf
* its not the client or server burp config

So if I have to reproduce the problem, its a clean burp install and follow http://burp.grke.org/docs/burp_ca.html.  I am wondering if the documentation is wrong or somehow I got confused. I pretty much copy/pasted the examples.

**Comment by laapsaap** [comment] 2015-07-28 15:47
So it was working on day one after installing the server, but somehow after a few days I am getting certification errors again.  Didnt change anything, right now I have no idea what is causing this.

**Comment by grke** [comment] 2015-07-28 21:28
Is it perhaps something to do with the clocks on your machines moving around, or something related to time. I remember, a long time ago with old versions of openssl, it didn't generate correct dates in the certificates.

To check that, you can run an openssl command to tell you what the start and end dates of your certificates are:
openssl x509 -noout -startdate -enddate -in ssl_cert-client.pem
openssl x509 -noout -startdate -enddate -in ssl_cert-server.pem

**Comment by laapsaap** [comment] 2015-07-29 09:30
Another fact is,  when I started with a clean /etc/burp directory. I made a backup of it, even before it generated any certs.

Now with my current /etc/burp directory I am getting key generation failures, if I use my clean backup burp directory and everything stays the same. (same client, same server).  The ssl handshake completes and its working.

So I can conclude it has to be something that change overtime in /etc/burp.

**Comment by laapsaap** [comment] 2015-07-29 09:39
Using configuration from /etc/burp/CA.cnf
Check that the request matches the signature
Signature ok
ERROR:Serial number 7C has already been issued,
      check the database/serial_file for corruption
The matching entry has the following details
Type      :Valid
Expires on    :350723120501Z
Serial Number :7C
File name     :unknown
Subject Name  :/CN=xxxx


What causes this? I am trying to generate the keys manually with burp_ca

**Comment by laapsaap** [comment] 2015-07-29 09:57
hmm i copied index.txt.old to index.txt and it seems to be working now.

**Comment by grke** [comment] 2015-08-07 10:57
Hello,
I think you are right, burp_ca makes no attempt to lock out simultaneous instances of itself, and never has done. I will fix this soon.

**Comment by grke** [comment] 2015-08-07 11:43
Hello,
If you are still able to reproduce the problem, can you try adding the following to the top of /usr/sbin/burp_ca, after the version comment and before 'set -e'?

[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -e -w 60 "$0" "$0" "$@" || :

**Comment by laapsaap** [comment] 2015-08-13 09:30
I have added this line in my burp_ca, I will try reproduce this problem. Thanks

**Comment by grke** [comment] 2015-08-13 11:24
I tried that line on ubuntu today. It didn't work because it has a different version of flock than I have on my arch system.
I had to specify a different lock file to the name of the script, like this:
[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -e -w 60 "$0".lock "$0" "$@" || :

Or like this:

[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -e -w 60 /etc/burp/CA/burp_ca.lock "$0" "$@" || :

**Comment by grke** [comment] 2015-08-20 22:36
Did it work?

**Comment by grke** [comment] 2015-08-29 03:41
Flocker change merged into git master.

**Closed by grke** 2015-08-29 03:41 UTC
Labels: Bug

**Comment by laapsaap** [comment] 2015-09-10 11:14
Problem with flock is, it isnt available on MacOS

**Comment by grke** [comment] 2015-09-10 12:51
Did you try:
https://github.com/discoteq/flock
