### ISSUE TITLE
2.1.26 win64 client: crash

### ISSUE THREAD

**Issue by remoe** [grke/burp#664] opened 2018-01-02 23:54 UTC
Event Viewer:

```
Faulting application name: burp.exe, version: 0.0.0.0, time stamp: 0x00000031
Faulting module name: ntdll.dll, version: 10.0.16299.64, time stamp: 0x493793ea
Exception code: 0xc0000374
Fault offset: 0x00000000000f87bb
Faulting process id: 0x2218
Faulting application start time: 0x01d384241d108f3c
Faulting application path: c:\Program Files\Burp\bin\burp.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 32be9b88-4f3b-4b77-9dc1-cbcf805376d3
Faulting package full name: 
Faulting package-relative application ID: 
```

client burp.conf (some value changed)

```
mode = client
server = x.x
port = 4971
cname = name
password = pw
include = d:/d1
include = d:/d2
include = d:/d3
include = w:/d4
include = w:/d5
exclude_regex = Google/Chrome
exclude_regex = AppData/Local/Microsoft/Windows
exclude_regex = AppData/Local/Android
exclude_regex = AppData/LocalLow/Sun
exclude_regex = AppData/LocalLow/Google
exclude_regex = AppData\Roaming\Apple Computer\MobileSync 
stdout = 1
progress_counter = 1
nobackup = .nobackup
lockfile = C:/Program Files/Burp/lockfile
ca_burp_ca = C:/Program Files/Burp/bin/burp_ca.bat
ca_csr_dir = C:/Program Files/Burp/CA
ssl_cert_ca = C:/Program Files/Burp/ssl_cert_ca.pem
ssl_cert = C:/Program Files/Burp/ssl_cert-client.pem
ssl_key = C:/Program Files/Burp/ssl_cert-client.key
ssl_key_password = password
ssl_peer_cn = burpserver
server_can_restore = 0
split_vss = 0
strip_vss = 0
encryption_password = pw
autoupgrade_os = win64
autoupgrade_dir = C:/Program Files/Burp/autoupgrade
vss_drives = cd
```
crash behavior:

```
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy 196608
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy 196672
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy 196736
yyyyyyy
```

Server Burp Linux Version: 2.1.24

**Comment by grke** [comment] 2018-01-03 07:04
Hello,
Are you able to reliably reproduce the crash?
Are you able to run the client in gdb? http://burp.grke.org/docs/debugging.html

**Comment by grke** [comment] 2018-01-03 07:05
What version is the client?

**Comment by remoe** [comment] 2018-01-03 07:49
2.1.26

**Comment by deajan** [comment] 2018-01-03 08:01
Tried to  put myself into the same config, windows x64 client 2.1.26 with server 2.1.24.
I am using protocol 2. Which one do you use ?

**Comment by remoe** [comment] 2018-01-03 08:05
I use protocol 1 and I can't reproduce the error with gdb. It runs awhile without crashing.

**Comment by remoe** [comment] 2018-01-03 08:18
no crash with gdb :/

```
New Thread 13304.0xb88]
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "Task Scheduler Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "VSS Metadata Store Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "Performance Counters Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "ASR Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "WMI Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "Shadow Copy Optimization Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "MSSearch Service Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "IIS Config Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "Registry Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "MSMQ Writer (MSMQ)", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] VSS Writer (BackupComplete): "COM+ REGDB Writer", State: 0x1 (VSS_WS_STABLE)
2018-01-03 09:15:06: c:\Program Files\Burp\bin\burp.exe[13304] backup finished ok
warning: Invalid parameter passed to C runtime function.


Program exited normally.
(gdb) bt
No stack.

```

**Comment by remoe** [comment] 2018-01-03 08:22
I backup also a network drive.

**Comment by grke** [comment] 2018-01-04 10:41
Are you able to reproduce the crash without gdb?

What do you mean by 'a network drive'?

**Comment by remoe** [comment] 2018-01-04 13:56
1) No, now it doesn't crash, but it hangs on:

```
Generate VSS snapshots.
Driver="VSS Vista", Drive(s)="CD"
```

2) I try to backup a windows network drive (w:) with burp

**Comment by grke** [comment] 2018-01-05 01:04
Hello,

I don't think backing up mapped drives on windows will work, see this:

https://github.com/grke/burp/issues/165

If the VSS snapshotting is hanging, maybe your VSS service needs to be restarted.

It is true that burp shouldn't segfault, but since the problem cannot be reproduced, I don't think I can help.

Here are some ideas of things you can do:

*) back up that drive directly on the real machine that contains that data
*) find a different way to back up that data
*) fix issue 165
*) wait for somebody/me to fix issue 165
*) sponsor me to fix issue 165
*) something else I didn't think of

**Comment by grke** [comment] 2018-01-08 09:18
This is basically issue 165, so closing.

**Closed by grke** 2018-01-08 09:18 UTC
