### ISSUE TITLE
Problem with protocol 2 since v2.1.14 in iobuf_relative_path_attack()

### ISSUE THREAD

**Issue by deajan** [grke/burp#786] opened 2018-12-17 17:59 UTC
Hello,

I have a burp server running protocol 2 on two different dedup groups.
Since upgrade to 2.1.14, one of the group clients cannot backup anymore with:

```
2018-12-14 09:52:00 +0100: burp[26559] Found interrupted backup.
2018-12-14 09:52:00 +0100: burp[26559] Will resume on the next backup request.
2018-12-14 09:52:00 +0100: burp[26559] Backup resumed
2018-12-14 09:52:00 +0100: burp[26559] Client version: 2.2.14
2018-12-14 09:52:00 +0100: burp[26559] Protocol: 2
2018-12-14 09:52:00 +0100: burp[26559] Client is Windows
2018-12-14 09:52:00 +0100: burp[26559] forked champ chooser pid 26573
2018-12-14 09:52:09 +0100: burp[26559] Could not connect to champ chooser on /storage/burp-protocol2/global/data/cc.sock after 3 attempts: No such file or directory
2018-12-14 09:52:09 +0100: burp[26559] could not connect to champ chooser
2018-12-14 09:52:09 +0100: burp[26559] problem connecting to champ chooser
2018-12-14 09:52:09 +0100: burp[26559] error in backup phase 2
2018-12-14 09:52:09 +0100: burp[26559] Backup failed
2018-12-14 10:12:00 +0100: burp[28190] Found interrupted backup.
2018-12-14 10:12:00 +0100: burp[28190] Will resume on the next backup request.
2018-12-14 10:12:00 +0100: burp[28190] Backup resumed
2018-12-14 10:12:00 +0100: burp[28190] Client version: 2.2.14
2018-12-14 10:12:00 +0100: burp[28190] Protocol: 2
2018-12-14 10:12:00 +0100: burp[28190] Client is Windows
2018-12-14 10:12:00 +0100: burp[28190] forked champ chooser pid 28200
2018-12-14 10:12:09 +0100: burp[28190] Could not connect to champ chooser on /storage/burp-protocol2/global/data/cc.sock after 3 attempts: No such file or directory
2018-12-14 10:12:09 +0100: burp[28190] could not connect to champ chooser
2018-12-14 10:12:09 +0100: burp[28190] problem connecting to champ chooser
2018-12-14 10:12:09 +0100: burp[28190] error in backup phase 2
2018-12-14 10:12:09 +0100: burp[28190] Backup failed
```

In cc.log of the dedup group I get:
```
2018-12-17 09:32:02 +0100: burp[24784] Got champ lock for dedup_group: global
2018-12-17 09:32:02 +0100: burp[24784] Not attempting to clean up unused data files
2018-12-17 09:32:02 +0100: burp[24784] because /storage/burp-protocol2/global/clients is resuming
2018-12-17 09:32:02 +0100: burp[24784] locked: sparse index
2018-12-17 09:32:02 +0100: burp[24784] unexpected command in iobuf_relative_path_attack(): F:0008:(binary data)
2018-12-17 09:32:02 +0100: burp[24784] Error reading /storage/burp-protocol2/global/data/sparse in candidate_load, pos 979608
2018-12-17 09:32:02 +0100: burp[24784] champ chooser exiting: -1
2018-12-17 09:52:01 +0100: burp[18804] Got champ lock for dedup_group: global
2018-12-17 09:52:01 +0100: burp[18804] Not attempting to clean up unused data files
2018-12-17 09:52:01 +0100: burp[18804] because /storage/burp-protocol2/global/clients is resuming
2018-12-17 09:52:01 +0100: burp[18804] locked: sparse index
2018-12-17 09:52:02 +0100: burp[18804] unexpected command in iobuf_relative_path_attack(): F:0008:(binary data)
2018-12-17 09:52:02 +0100: burp[18804] Error reading /storage/burp-protocol2/global/data/sparse in candidate_load, pos 979608
2018-12-17 09:52:02 +0100: burp[18804] champ chooser exiting: -1
```

I guess the path_attack() problem has something todo with the latest security patches introduced with 2.2.14.

Here's my client config file if it may help, especially the windows_settings part that may not work anymore ?

```
password=verylongpassword
. incexc/std_settings
include = C:/Users/User/Desktop
include = C:/Users/User/Documents
include = C:/Users/User/Pictures
include = C:/Users/User/Downloads
include = C:/Users/User/Videos
include = C:/Users/User/AppData/Local/Microsoft/Outlook
include = C:/MAILS
label = email_address : my@mail.address
soft_quota = 120GB
```

and here are the include files

std_settings
```
. audio_compressed
. image_compressed
. video_compressed
. generic_compressed

. windows_settings

nobackup=.nobackup
atime=0
scan_problem_raises_error=0
exclude_ext=tmp
```

audio_compressed
```
exclude_comp=mp3
exclude_comp=wma
exclude_comp=ogg
[...]
```

I do not include the other _compressed files since they all only have exclude_comp statements.

windows_settings
```
exclude_regex = "[A-Z]:/Users/[^/]+/AppData/Local/Temp"
exclude_regex = "[A-Z]:/Documents and Settings/[^/]+/Cookies"
exclude_regex = "[A-Z]:/Documents and Settings/[^/]+/Recent"
exclude_regex = "[A-Z]:/Documents and Settings/[^/]+/Local Settings/Temp"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Temp"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/History"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Application Data"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Temporary Internet Files"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Microsoft/Internet Explorer"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Microsoft/Windows/Temporary Internet Files"
# Error reports
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Microsoft/Windows/WER"
# Windows 10 Edge cache
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Microsoft/Windows/InetCache"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Microsoft/Windows/WebCache"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Microsoft/Windows/AppCache"

exclude_regex="[A-Z]:/Users/[^/]+/AppData/Roaming/Microsoft/Windows/Cookies"
exclude_regex="[A-Z]:/Users/[^/]+/NetHood"
exclude_regex="[A-Z]:/Users/[^/]+/PrintHood"
exclude_regex="[A-Z]:/Users/[^/]+/Cookies"
exclude_regex="[A-Z]:/Users/[^/]+/Recent"
exclude_regex="[A-Z]:/Users/[^/]+/SendTo"
exclude_regex="[A-Z]:/Users/[^/]+/LocalService"
exclude_regex="[A-Z]:/Users/[^/]+/NetworkService"
exclude_regex="[A-Z]:/*/MSOCache"
exclude_regex="[A-Z]:/*/Config.Msi"
exclude_regex="[A-Z]:/*Thumbs.db"

# Chrome, Opera and Firefox temporary files
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Google/Chrome/User Data/Default/Cache"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Opera/Opera/profile/cache4"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Opera Software/Opera Stable/Cache"
exclude_regex="[A-Z]:/Users/[^/]+/AppData/Local/Mozilla/Firefox/Profiles/[^/]+/Cache"

# Windows downloads
#exclude_regex="[A-Z]:/Users/[^/]+/Downloads"


# Windows update cache
exclude_regex="C:/Windows/SoftwareDistribution/Download"
exclude_regex="C:/Windows/Temp"
exclude_regex="C:/Windows/Downloaded Program Files"
exclude_regex="[A-Z]:/RECYCLER"
exclude_regex=^[A-Z]:/\$recycle\.bin$
exclude_regex="[A-Z]:/System Volume Information"
# swap file (Windows XP, 7, 8)
exclude_regex="[A-Z]:/pagefile.sys"
# swap file?? (Windows 8)
exclude_regex="[A-Z]:/swapfile.sys"
exclude_regex=^[A-Z]:/hiberfil\.sys$
# Windows temp installer
exclude_regex="[A-Z]:/$WINDOWS.~BT"
# Windows 10 Upgrade previous install
exclude_regex=[A-Z]:/Windows.old$

# MacOS files
exclude_regex=\.DS_Store

split_vss=0
strip_vss=1
```

Willing to do tests if needed, I can also compile a test patch in order to check.

**Comment by melak** [comment] 2018-12-17 21:32
I am pretty sure I have hit this too ("could not connect to champ chooser" certainly sounds familiar), although I did not save the logs (I reverted to 2.2.12 until I have a chance to do debug it).

**Comment by githubcdr** [comment] 2018-12-20 15:03
confirmed here too

```
+0100: burp[14805] Tried to read 33 bytes, got 25 by pass 1
+0100: burp[14805] Error in fzp_read_ensure, called from do_iobuf_fill_from_fzp: 25 bytes, eof
+0100: burp[14805] Error attempting to read after S0020 in do_iobuf_fill_from_fzp (S:32)
+0100: burp[14805] Error reading /backup/burp/global/clients/node1.lan/working/changed/0000000E in hash_load
+0100: burp[14805] champ chooser exiting: -1
+0100: burp[16278] Got champ lock for dedup_group: global

```

**Comment by grke** [comment] 2018-12-21 07:50
Hello,

Sorry for the delay, real life happens a lot at this time of the year.

I think the problem is in src/sbuf.c. It shouldn't do the iobuf_relative_path_attack(rbuf) on CMD_FINGERPRINT:

```
                case CMD_FINGERPRINT:
                        if(blk && blk_set_from_iobuf_fingerprint(blk, rbuf))
                                return PARSE_RET_ERROR;
                        // Fall through.
                case CMD_MANIFEST:
                        if(iobuf_relative_path_attack(rbuf))
                                return PARSE_RET_ERROR;
                        iobuf_free_content(&sb->path);
                        iobuf_move(&sb->path, rbuf);
                        return PARSE_RET_COMPLETE;

```

The fix would be to copy this part into the bottom of CMD_FINGERPRINT and not fall through:
```
                        iobuf_free_content(&sb->path);
                        iobuf_move(&sb->path, rbuf);
                        return PARSE_RET_COMPLETE;
```

**Comment by grke** [comment] 2018-12-21 07:51
Patch coming soon.

**Comment by deajan** [comment] 2018-12-21 07:57
I just recompiled with that patch. I'll let you know when next client connects.

**Comment by githubcdr** [comment] 2018-12-21 08:08
I tried the patch and it seems to be working.

**Comment by grke** [comment] 2018-12-21 08:12
Works for me too, sorry for breakage.
Looks like I need more test coverage on that.

**Comment by deajan** [comment] 2018-12-21 11:06
Late for the party, works for me too :)

**Comment by grke** [comment] 2018-12-21 22:36
Fixed in master. Will maybe try to do a quick release.

**Closed by grke** 2018-12-21 22:36 UTC

**Comment by deajan** [comment] 2018-12-23 10:14
Sorry to ask, but did you forget to push the commit to github ?

**Comment by grke** [comment] 2018-12-24 10:40
Hello,
Good point.
I pushed, but I messed up a merge conflict so it failed.
Having to run through the automatic tests again, should be ready in about an hour.

**Comment by grke** [comment] 2018-12-27 06:03
Hello,
Sorry, I got delayed by crazy things going on at Christmas.
The fixes are definitely in master now, and I will do a release for New Year's.
Thanks for prompting me.

**Comment by deajan** [comment] 2018-12-27 14:50
Thanks, hope your Christmas was lit :)
