### ISSUE TITLE
Incremental problem

### ISSUE THREAD

**Issue by Yohann55** [grke/burp#546] opened 2017-03-20 14:45 UTC
Hello,
I have a problem with Burp. It backup everythink every day.
Example: in Folder Serveur1, I have:
217G   0000001 2017-03-15 17:05:31
228G   0000002 2017-03-16 19:18:12
75G     0000003 2017-03-19 17:18:10
0          current
0          lockfile
0          working

The last day is only 75G because the drive is full.
My config:
keep = 7
hardlinked_archive = 0

I have understood that Burp backup only the new file and the modificated file? I'm wrong?
I have 3 server with about 220G each, so it's not possible to backup all the file every day...

Thank you

**Comment by grke** [comment] 2017-03-21 11:32
Hello,
What are you using to find out the sizes of the storage directories?

**Comment by Yohann55** [comment] 2017-03-21 14:08
Hello,

I use:
du -sh *

**Comment by grke** [comment] 2017-03-22 09:57
OK, thanks.

Also:
What version are you using on the server and client?
Is your burp client encrypting the files?
Is librsync = 0 or 1?

New files are always backed up as they haven't been seen before.
A file whose path has changed since last backup will be new if its path has changed.

Modified files are detected if the path exists in the previous backup, but the mtime is different.
 
Modified files may be treated as new files if they are encrypted, or librsync = 0.
Otherwise, modified files will be transferred using librsync.

**Comment by grke** [comment] 2017-03-22 10:00
Maybe you can find a file that you think shouldn't have been backed up twice, and compare the manifest entries for it. And find the location in the backup directory for that file in both backups.

**Comment by Yohann55** [comment] 2017-03-22 10:31
Thank you
Version is 2.1.4
For me there are no encrypting, I use default config. I don"t find librsync = 0 or 1 (I have looked in burp.conf, burp-server.conf)
I will compare the different backup to see the difference between the file.
I backup about 600 Gb, and my hard drive for burp is 1.5 Tb perhaps it is too small?

**Comment by grke** [comment] 2017-03-23 21:31
I might have broken something in 2.1.2 when I refactored some code.

**Comment by Yohann55** [comment] 2017-03-24 08:04
I have comparded the folder beetwen day 2 et day 3:
/Sauvegarde/serveur1$ du -sh *
228G	0000001 2017-03-21 19:44:08
221G	0000002 2017-03-22 19:44:07
0	current

/Sauvegarde/serveur2$ du -sh *
60G	0000001 2017-03-21 19:47:08
136G	0000002 2017-03-22 19:47:07
0	current

/Sauvegarde/serveur4$ du -sh *
125G	0000001 2017-03-21 19:48:08
254G	0000002 2017-03-22 19:48:07
0	current

===================================

/Sauvegarde/serveur1$ du -sh *
228G	0000001 2017-03-21 19:44:08
135G	0000002 2017-03-22 19:44:07
222G	0000003 2017-03-23 19:44:05
0	current

/Sauvegarde/serveur2$ du -sh *
60G	0000001 2017-03-21 19:47:08
25G	0000002 2017-03-22 19:47:07
136G	0000003 2017-03-23 19:47:06
0	current

/Sauvegarde/serveur4$ du -sh *
125G	0000001 2017-03-21 19:48:08
168G	0000002 2017-03-22 19:48:07
254G	0000003 2017-03-23 19:48:05
0	current

For an example, I have on Serveur1, a file with last day of modification : 12/07/2016. But this file is in the 3 backup. And it's the same for many many file.

Thank you for your help :)

**Comment by grke** [comment] 2017-03-25 03:35
Hello,

I have tried to reproduce this problem, but I am unable to do so. So, I need more information.

What kind of computer is "Serveur1"?
When you say "this file is in the 3 backup", where are you seeing it?
Are you looking in the manifest? Or are you looking at actual files inside the backup storage directory?
Where are you seeing the modification time?

These things would be useful for you to post:

For the file in each of the three backups:
ls -l <path to file>
And post the output.

And, for each of the three backups, use a tool like 'zless' to find the path of the file inside manifest.gz. Post the section (about 10 lines) of the manifest.gz that you find here.

**Comment by Yohann55** [comment] 2017-03-27 07:19
Hello,

What kind of computer is "Serveur1"?
serveur1, 2 and 4 are under Windows server 2003 et 2008

When you say "this file is in the 3 backup", where are you seeing it?
I see that in : "date of backup"/data/t/C:/directory/

Where are you seeing the modification time?
On the Windows server : Right click => Propriety

For manifest.gz:
Day 1
t001Ft/C:/CDWPrg/suiteexpert (5).exe
r0034A A IH/ B A A A bXx0g A A BYxtWG BXhLvd BX7NFA A g J
f001DC:/CDWPrg/suiteexpert (5).exe
x002A459218634:73d51e029c243a750a83b1e6d99063f9
t001Bt/C:/CDWPrg/suiteexpert.pdf
r0033A A IH/ B A A A EF4g A A BX2f6c BSOAWG BSOAWF A g J
f0019C:/CDWPrg/suiteexpert.pdf
x00281073098:7ad2752f318d9e7893d1865507f744b3

ls -l give:
-rw-r--r-- 1 root root 453366726 mars  21 19:59 suiteexpert (5).exe
-rw-r--r-- 1 root root    880925 mars  21 19:59 suiteexpert.pdf



Day 2
t001Ft/C:/CDWPrg/suiteexpert (5).exe
r0034A A IH/ B A A A bXx0g A A BYxtWG BXhLvd BX7NFA A g J
f001DC:/CDWPrg/suiteexpert (5).exe
x002A459218634:73d51e029c243a750a83b1e6d99063f9
t001Bt/C:/CDWPrg/suiteexpert.pdf
r0033A A IH/ B A A A EF4g A A BX2f6c BSOAWG BSOAWF A g J
f0019C:/CDWPrg/suiteexpert.pdf
x00281073098:7ad2752f318d9e7893d1865507f744b3

ls -l give:
-rw-r--r--  1 root root 453366726 mars  22 19:55 suiteexpert (5).exe
-rw-r--r--  1 root root    880925 mars  22 19:55 suiteexpert.pdf


Day 3
t001Ft/C:/CDWPrg/suiteexpert (5).exe
r0034A A IH/ B A A A bXx0g A A BY06e2 BXhLvd BX7NFA A g J
f001DC:/CDWPrg/suiteexpert (5).exe
x002A459218634:73d51e029c243a750a83b1e6d99063f9
t001Bt/C:/CDWPrg/suiteexpert.pdf
r0033A A IH/ B A A A EF4g A A BX2f6c BSOAWG BSOAWF A g J
f0019C:/CDWPrg/suiteexpert.pdf
x00281073098:7ad2752f318d9e7893d1865507f744b3

ls -l give:
-rw-r--r--  1 root root 453366726 mars  23 19:56 suiteexpert (5).exe
-rw-r--r--  1 root root    880925 mars  23 19:56 suiteexpert.pdf

**Comment by grke** [comment] 2017-03-27 08:06
Thanks for the information.

I have now reproduced the problem on my debian machine. It is definitely 2.1.2 that breaks it.
Hopefully I can make a fix for this soon.

**Comment by grke** [comment] 2017-03-27 11:33
This is now fixed in master.
Thanks for the report.
Closing.

**Closed by grke** 2017-03-27 11:33 UTC

**Comment by Yohann55** [comment] 2017-03-27 12:40
Thank you for your quick responsiveness :)
