### ISSUE TITLE
[burp 2] Protocol 2 Not keeping versions over a week old

### ISSUE THREAD

**Issue by computerfr33k** [grke/burp#417] opened 2016-04-02 13:33 UTC
It seems as if the server is not honoring my specified versioning.
I have the following in my server config:
```bash
# You can have as many 'keep' lines as you like.
# For example, if running backups daily, setting 7, 4, 6 will keep
# 7 daily backups, 4 weekly, and 6 four-weekly backups.
keep = 7
keep = 4
keep = 6
```
But it's only keeping the most recent weeks worth
```bash
Backup: 0000038 2016-03-27 23:10:42
Backup: 0000039 2016-03-28 23:09:21
Backup: 0000040 2016-03-29 19:23:09
Backup: 0000041 2016-03-30 19:01:47
Backup: 0000042 2016-04-01 02:26:11
Backup: 0000043 2016-04-01 10:26:44
Backup: 0000044 2016-04-01 10:32:00
Backup: 0000045 2016-04-02 06:37:24
```

**Comment by grke** [comment] 2016-04-02 22:26
Hello,

What version is your server?
When did you set those keep values?
Do any of the backup storage directories on the server contain a file called 'hardlinked_archive'?

**Comment by computerfr33k** [comment] 2016-04-03 17:41
* Version: 2.0.34
* Values have been set ever since I started using it.
* There are files called hardlinked in the <burp-backup-root/client/backup#> but not under the global folder(s)

**Comment by grke** [comment] 2016-04-03 21:57
Hello,

I am highly confident that burp-2.0.34 respects keep values correctly, because I have automatic testing in place that tests that mechanism every time I push a new patch and every time I do a release.
The automatic tests for this can be found in utest/server/test_delete.c if you want to look at them.

I also manually tested just now (by installing 2.0.34 and running several backups), and observed
that it was working correctly:

drwxr-xr-x 3 root root 4096 Apr  4 07:36 0000001 2016-04-04 07:36:40
drwxr-xr-x 3 root root 4096 Apr  4 07:47 0000029 2016-04-04 07:47:20
drwxr-xr-x 3 root root 4096 Apr  4 07:50 0000036 2016-04-04 07:49:55
drwxr-xr-x 3 root root 4096 Apr  4 07:51 0000043 2016-04-04 07:51:11
drwxr-xr-x 3 root root 4096 Apr  4 07:52 0000050 2016-04-04 07:52:12
drwxr-xr-x 2 root root 4096 Apr  4 07:53 0000054 2016-04-04 07:52:43
drwxr-xr-x 2 root root 4096 Apr  4 07:53 0000055 2016-04-04 07:52:54
drwxr-xr-x 2 root root 4096 Apr  4 07:53 0000056 2016-04-04 07:53:01
drwxr-xr-x 3 root root 4096 Apr  4 07:53 0000057 2016-04-04 07:53:08
drwxr-xr-x 2 root root 4096 Apr  4 07:53 0000058 2016-04-04 07:53:19
drwxr-xr-x 2 root root 4096 Apr  4 07:53 0000059 2016-04-04 07:53:26
drwxr-xr-x 3 root root 4096 Apr  4 07:53 0000060 2016-04-04 07:53:31
drwxr-xr-x 5 root root 4096 Apr  4 07:53 0000061 2016-04-04 07:53:38


You should only have a 'global' folder if you have used protocol 2 at some point.

If you run this command on the server, you will be able to see what is currently set for the given
client on the server-side. If you have configured the 'keep' settings correctly, you will see them in
the output:
burp -t -c /etc/burp/burp-server.conf -C <clientname>

**Comment by computerfr33k** [comment] 2016-04-03 23:12
I am getting this error when doing a backup and it processess it, not sure if it might be related to this.
And, I am also using protocol 2 as well. It also deletes the oldest backup every time I do a new one.

```bash
2016-04-03 18:01:25: burp[11634] Got sparse lock
2016-04-03 18:01:30: burp[11634] regenerate_client_dindex could not hard link '/mnt/1TB-ExtHDD/burp-backup/global/clients/eric-laptop/0000043 2016-04-01 10:26:44/manifest/dfiles' to '/mnt/1TB-ExtHDD/burp-backup/global/clients/eric-laptop/dindex/380000001C': File exists
2016-04-03 18:01:30: burp[11634] exit child
```

I am going to see if it works after clearing out my existing backups.

**Comment by grke** [comment] 2016-04-04 00:14
That hard link problem looks like a bug in protocol 2.
I recommend that you don't use protocol 2 for anything but play.

What do you get if you run this on the server:
burp -t -c /etc/burp/burp-server.conf -C eric-laptop ?

**Comment by computerfr33k** [comment] 2016-04-04 02:23
http://slexy.org/view/s2CZR4hyEB

**Comment by grke** [comment] 2016-04-04 09:46
It looks like the config is fine.

I am very very confident that the retention/deletion code is good, because I have automated tests for it, and it has been unchanged for about 5 years without anybody else having a problem like this.

I would guess one of the following is true:

*) You only set the config to be 7/4/6 recently, or
*) You set 7/4/6 at the start, then changed it to 7 briefly, then back to 7/4/6, or
*) The backups were deleted manually via the client.

If you are using librsync=1 (the default), and you have made quite a few backups with keep=7, then switch to 7/4/6, it might be a few days before the oldest backup is 'hardlinked' and can stand alone. Until then, the oldest backups will get deleted one by one. This might be the case with what you are seeing. Which of your backup directories have a 'hardlinked' file in them?

Otherwise, If you can tell me exactly how to reproduce your problem, then I will be able to investigate more.
Even better would be if you could add a test case to utest/server/test_delete.c that demonstrates a problem.

The dindex thing looks like a real problem, so I will try to investigate that.

**Comment by computerfr33k** [comment] 2016-04-05 05:30
So, I just deleted all of my protocol 2 backups to start from scratch. Ran 15 backups and it still doesn't keep over 8 backups.
Protocol 1 does work perfectly, which it's supposed too since its the stable protocol.
I am no longer seeing any 'hardlinked' file in the client directory for protocol 2.

```bash
2016-04-05 00:17:16: burp[6832] Server has protocol=0 (auto)
2016-04-05 00:17:16: burp[6832] Using protocol=2
Backup: 0000008 2016-04-04 23:51:58
Backup: 0000009 2016-04-04 23:52:37
Backup: 0000010 2016-04-04 23:53:28
Backup: 0000011 2016-04-04 23:55:51
Backup: 0000012 2016-04-05 00:03:42
Backup: 0000013 2016-04-05 00:09:41
Backup: 0000014 2016-04-05 00:11:23
Backup: 0000015 2016-04-05 00:13:37
```

**Comment by grke** [comment] 2016-04-05 21:19
OK, I reproduced it. It is a protocol2 only problem.

'Hardlinked' has no meaning in protocol2, so it doesn't generate 'hardlinked_archive' files, which means that the deletion code isn't able to keep multiple periods of backups because it is looking for
'hardlinked_archive' files in order to find the boundaries.

I just need to update the code to not worry about  'hardlinked_archive' when in protocol2 mode, and fix
the test so it doesn't generate them for protocol2 backups.

Thanks for your report.

**Comment by grke** [comment] 2016-04-06 12:56
I have now fixed the problem in master, and fixed the protocol2 delete tests too.

**Closed by grke** 2016-04-06 12:56 UTC
