### ISSUE TITLE
2.1.22 test failure: utest/builders/build_asfd_mock.c:77:F:Core:test_phase2_with_slist_changed_files:0: Assertion 'wbuf->len==expected->len' failed

### ISSUE THREAD

**Issue by mkszuba** [grke/burp#638] opened 2017-11-06 09:45 UTC
See the topic. Observed on Linux/amd64, both in a Docker container and under bare-metal OS installation.

Let me know if you need any additional information.

**Comment by grke** [comment] 2017-11-06 20:48
Hello,
What version of librsync do you have?

**Comment by grke** [comment] 2017-11-07 12:25
Sorry, didn't mean to close this.

**Comment by mkszuba** [comment] 2017-11-08 07:38
2.0.0

**Comment by grke** [comment] 2017-11-08 08:47
OK, thanks. I am pretty sure that I know what the problem is. I previously changed the test to cope with an issue with librsync 2.0.1, but I assumed the issue was present with librsync 2.0.0 too.

Can you try changing this file:

utest/client/protocol1/test_backup_phase2.c

On line 229, it looks like this:

const char *lrv="librsync 2.";

Change it to:

const char *lrv="librsync 2.0.1";

If the test then passes, we will know that the librsync behaviour has changed between 2.0.0 and 2.0.1, and I can come up with a proper fix to the test.

**Comment by mkszuba** [comment] 2017-11-08 10:15
That *does* help.

**Comment by grke** [comment] 2017-11-11 10:58
Thanks for the help, a fix is now in master that should solve the problems for all versions of librsync.

**Closed by grke** 2017-11-11 10:58 UTC
